language: android
android:
  components:
    - build-tools-23.0.1
    - tools
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
script: ./gradlew clean build