language: android

android:
    components:
        - build-tools-23.0.1
        - tools
        - android-23
        - extra-android-support
        - extra-android-m2repository

licenses:
    - 'android-sdk-license-.+'

jdk:
    - oraclejdk8

install: true

script: ./gradlew clean build

branches:
    except:
        - gh-pages

notifications:
    email: false

sudo: false

cache:
    directories:
        - $HOME/.gradle